server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:file:./data/payment-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
#    We don't need below config as it is already set via code. check config/KafkaConsumerConfig.java (line 37-50)
#    consumer:
#      group-id: payment-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.ecommerce"

outbox:
  polling:
    enabled: true
    interval-ms: 2000        # Poll every 2 seconds
    batch-size: 100          # Max events per poll
    max-retries: 3           # Max retries before marking as FAILED
    retry-backoff-ms: 1000   # Backoff time between retries

logging:
  level:
    root: INFO
    com.ecommerce.payment: INFO
